version: '3.9'
services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
        - wordpress:/var/www/html
    restart: always
    ports:
      - 443:443
    networks:
      - inception
  mariadb:
    build: requirements/mariadb
    volumes:
        - wp-data:/var/lib/mysql
    restart: always
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    volumes:
        - wordpress:/var/www/html
    restart: always
    networks:
      - inception
  redis:
    build: requirements/bonus/redis
    restart: always
    networks:
      - inception
  vsftpd:
    build: requirements/bonus/ftp
    restart: always
    networks:
      - inception
  # portfolio:
  #   build: requirements/bonus/portfolio
  #   restart: always
  #   networks:
  #     - inception

volumes:
  wordpress:
    driver : local
  wp-data:
    driver : local
networks:
  inception:
    driver : bridge