version: '3.9'
services:
  nginx:
    build: requirements/nginx
    volumes:
        - wordpress:/var/www/html
    ports:
      - 1337:80
    networks:
      - inception

  mysql:
    build: requirements/mariadb
    volumes:
        - wp-data:/var/lib/mysql
    restart: always
    networks:
      - inception
  wordpress:
    depends_on:
      - mysql
    build: requirements/wordpress
    volumes:
        - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    driver : local
networks:
  inception:
    driver : bridge