version: '3'
services:
  nginx:
    image: nginx:1.0
    ports:
      - "443:443"
    volumes:
        - ./nginx:/etc/nginx/default
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
    links:
        - wordpress
    restart: always
    networks:
      - inception
  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=selhanda
    links:
        - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    image: mariadb:1.0
    ports:
      - "3306:3306"
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=selhanda
    restart: always
    networks:
      - inception
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: selhanda
      MYSQL_PASSWORD: selhanda
    volumes:
      - ./app:var/www/html
    networks:
      - inception
networks:
  inception:
    driver: "bridge"
volumes:
  data:
    driver: "local"
