version: '3'
services:
  nginx:
    image: nginx:1.0
    ports:
      - "443:443"
    volumes:
      - ./app:/var/www/html
    networks:
      - inception
  wordpress:
    image: data/wordpress:1.3
    ports:
      - "3000:3000"
    volumes:
      - ./app:var/www/html
    networks:
      - inception

  mariadb:
    image: mariadb:1.0
    ports:
      - "3306:3306"
    volumes:
      - data/mariadb
    networks:
      - inception
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: selhanda
      MYSQL_PASSWORD: selhanda
    volumes:
      - ./app:var/www/html
    networks:
      - inception
networks:
  inception:
    driver: "bridge"
volumes:
  data:
    driver: "local"
