version: '3.9'
services:
  nginx:
    image: nginx:1.3
    user: root
    container_name: nginx
    ports:
      - "443:443"
    volumes:
        - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
        - ./requirements/wordpress:/var/www/html
    links:
        - wordpress
    restart: always
    networks:
      - inception
  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    container_name: wordpress
    ports:
        - "9000:9000"
    volumes:
        - ./requirements/wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=selhanda
    links:
        - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    user: root
    ports:
      - "3306:3306"
    volumes:
        - ./requirements/mariadb:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=selhanda
    restart: always
    networks:
      - inception
networks:
  inception:
    driver: "bridge"
volumes:
  data:
    driver: "local"
