version: '3.9'
services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
        - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    ports:
      - 443:443
    container_name: nginx
    networks:
      - inception
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
        - wp-data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - inception
  redis:
    build: requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
  vsftpd:
    build: requirements/bonus/ftp
    ports:
      - 21:21
    container_name: vsftpd
    restart: always
    volumes:
        - wordpress:/home/ftpuser/
    networks:
      - inception
  portfolio:
    build: requirements/bonus/portfolio
    ports:
      - 80:80
    container_name: portfolio
    restart: always
    networks:
      - inception
  adminer:
    build: requirements/bonus/adminer
    ports:
      - 8000:8000
    container_name: adminer
    restart: always
    networks:
      - inception
  portainer:
    build: requirements/bonus/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
    networks:
      - inception

volumes:
  wordpress:
    driver : local
  wp-data:
    driver : local
networks:
  inception:
    driver : bridge